FROM python:latest 
WORKDIR /api
RUN pip install gunicorn
ENV SECRET_KEY django-insecure-jfalh_%+a9ub@h*vrc*ws^et6*8-7*e56yzqj8g(pno-(iu^47
ENV ENV DEV
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
COPY ./requirements.txt ./requirements.txt
RUN pip install -r requirements.txt
COPY . . 
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]