name: Deploy On AWS 

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::123456789012:role/my-github-actions-role
          aws-region: us-east-1

      - name: Login to aws
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Build & Push Docker image to AWS ECR
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: comercify-api
          IMAGE_TAG: ${{ github.sha }}


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to AWS Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version --application-name your_application_name --version-label $GITHUB_SHA \
            --source-bundle S3Bucket=$BUCKET_NAME,S3Key=$GITHUB_SHA.zip

          aws elasticbeanstalk update-environment --environment-name your_environment_name \
            --version-label $GITHUB_SHA
        env:
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BUCKET_NAME: elasticbeanstalk-us-east-1-478521433580
