name: Deploy On AWS 

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t $DOCKER_IMAGE DockerFile.prod

      - name: Push Docker image to AWS ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry: 478521433580.dkr.ecr.us-east-1.amazonaws.com/comercify-api
        env:
          ECR_REGISTRY: 478521433580.dkr.ecr.us-east-1.amazonaws.com/comercify-api
          AWS_REGION: us-east-1
          DOCKER_IMAGE: comercify-api
      - run: docker tag $DOCKER_IMAGE $ECR_REGISTRY/$DOCKER_IMAGE
      - run: docker push $ECR_REGISTRY/$DOCKER_IMAGE

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to AWS Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version --application-name your_application_name --version-label $GITHUB_SHA \
            --source-bundle S3Bucket=$BUCKET_NAME,S3Key=$GITHUB_SHA.zip

          aws elasticbeanstalk update-environment --environment-name your_environment_name \
            --version-label $GITHUB_SHA
        env:
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BUCKET_NAME: elasticbeanstalk-us-east-1-478521433580
